[project]
name = "alfacrm"
version = "0.1.0"
description = "Is an asynchronous implementation for AlfaCRM API"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "aiohttp>=3.12.15",
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
    "pytest-stub>=1.1.0",
]
